config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # sidekiq
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  # letter_opener
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  # root to: "home#index"
  root to: "articles#index"

  # devise controllerへの設定
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }
  get '/users/sign_out' => 'devise/sessions#destroy'

  resources :articles, only: [:index, :show, :new, :create] do
    resource :like, only: [:show, :create, :destroy]
    # resources :comments, only: [:index, :new, :create]
    resources :comments, only: [:new, :create, :index]
  end

  resource :timeline, only:[:show]

  resources :accounts, only: [:show, :edit] do
    # ajax用
    resource :hasfollow, only: [:show]

    resources :followings, only: [:index]
    resources :followers, only: [:index]

    # フォロー機能用
    resources :follows, only: [:create]
    # フォロー解除機能用
    resources :unfollows, only: [:create]
  end

  # resource :profile, only: [:show, :update, :create, :destroy]
  resource :profile, only: [:show, :update]
end

app/views/commons/_alert.html.haml
-# = render 'commons/alert', {notice: notice, alert: alert}
%p.notice= notice
%p.alert= alert

app/views/commons/_article.html.haml
.container
    .page-insta
        = image_tag 'insta-mark.png'
    = render 'commons/tabs'
    - articles.each do |article|
        = render 'commons/articles', article: article
    .article-create
        = link_to new_article_path do
            %i.fa-solid.fa-circle-plus.fa-3x

=  javascript_pack_tag 'articleIndex'

app/views/commons/_articles.html.haml
.article-item#article-index{ data: { article_id: article.id } }
    .article-item-wrapper
        .article-item-left
            = link_to account_path(article.user) do
                = image_tag article.user.avatar_image(article.user)
        .article-item-right
            %p.article-item-right-name=article.user.account
            -# %p.article-item-right-time=article.updated_at
            -# %time(datetime="#{article.created_at}")= time_ago_in_words(article.created_at)
            %p.article-item-right-time=article.display_created_at
    - if article.images.present?
        .swiper
            .swiper-wrapper
                - article.images.each do |image|
                    .swiper-slide 
                        = image_tag image
            .swiper-pagination
            .swiper-button-prev
            .swiper-button-next
            .swiper-scrollbar
    .article-item-wrapper.mt-mark
        .article-item-mark
            .article-item-mark-heart.hidden.active-heart
                = image_tag 'heart-active.png'
            .article-item-mark-heart.hidden.inactive-heart
                = image_tag 'heart.png'
        .article-item-mark
            = link_to article_comments_path(article), id: 'comment-link'  do 
                = image_tag 'comment-mark.png'
        .article-item-mark

            = link_to "https://twitter.com/intent/tweet?url=#{request.url}&text=#{article.content}" do
                = image_tag 'link-mark.png'
    .article-item-text
        %p= article.content

app/views/commons/_back.html.haml
-# = render 'commons/back'
- if !current_page?(root_path)
    .back-btn
        -# = link_to :back do
        = link_to root_path do
            -# = image_tag 'back.png'
            %i.fa-solid.fa-arrow-left-long

app/views/commons/_flash.html.haml
-# = render 'commons/flash', flash: flash
- if flash.present?
    .flash
        - flash.each do |key,val|
            %div{:class => key}= val

app/views/commons/_follow.html.haml
.follow
    .container
        .follow-header-left
            = link_to :back do
                %i.fa-solid.fa-arrow-left-long
        %h1.page-header= header_name
        .follow-container
            -# - @user.each do |user|
            - users.each do |user|
                .follow-container-item
                    .follow-container-item-warapper
                        .follow-container-item-left
                            = link_to account_path(user) do
                                = image_tag user.avatar_image(user)
                        .follow-container-item-right
                            %p.name= user.account
                            %p.time Last seen 3 hours ago

app/views/commons/_followpage.html.haml
.follow
    .container
        .follow-header-left
            = link_to :back do
                %i.fa-solid.fa-arrow-left-long
        %h1.page-header= header_name
        .follow-container
            -# - @user.each do |user|
            - users.each do |user|
                .follow-container-item
                    .follow-container-item-warapper
                        .follow-container-item-left
                            = link_to account_path(user) do
                                = image_tag user.avatar_image(user)
                        .follow-container-item-right
                            %p.name= user.account
                            %p.time Last seen 3 hours ago

app/views/commons/_profile.html.haml
-# .container#profile-show{ data: {user_id: user.id, current_user_id: current_user.id}}
- if current_user.present?
    .container#profile-show{ data: {user_id: user.id , current_user_id: current_user.id}}
- else
    .container#profile-show{ data: {user_id: user.id}}
.profile-warapper
    .profile-warapper-left
        = link_to :back do
            %i.fa-solid.fa-arrow-left-long
    %h1.profile-warapper-center= user.account
    -# - if user != current_user
    - if current_page?(account_path(user)) 
        .profile-warapper-right
            - if current_user.present?
                -# = link_to 'UnFollow', account_unfollows_path(user), data: {method: 'post'}, class: 'profile-warapper-right-unfollow hidden'
                -# = link_to 'Follow', account_follows_path(user), data: {method: 'post'}, class: 'profile-warapper-right-follow hidden'
                %p.profile-warapper-right-unfollow.hidden UnFollow
                %p.profile-warapper-right-follow.hidden Follow
.page-header-right
-# - if user_signed_in? 
- if user.signed_in? 
    -if current_page?(profile_path)
        .header-logout
            = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete'}
.profile-avatar
    = image_tag user.avatar_image(user),id: 'top-avatar-img',  data: { type: 'editable' }
.profile-number
    .profile-number-item.post
        -# = '44'
        = user.articles.count
        %br/
        %p Posts
    = link_to account_followers_path(user), class: 'profile-number-item' do
        .profile-number-item-follower
            -# = '110'
            = user.followers.count
            %br/
            %p Followers
    = link_to account_followings_path(user), class: 'profile-number-item' do
        .profile-number-item-following
            -# = '44'
            = user.followings.count
            %br/
            %p Following
- i = 1
.profile-content
    - user.articles.each do |article|
        - break if i == 7
        -# - if article.images.present?
        - article.images.each do |image|
            - break if i == 7
            - if i == 1
                .profile-content-item.big-box-left
                    = image_tag image
            - elsif i == 6
                .profile-content-item.big-box-right
                    = image_tag image
            - else
                .profile-content-item
                    = image_tag image
            - i += 1
=  javascript_pack_tag 'profile'
-# =  javascript_pack_tag 'follow'

app/views/commons/_tabs.html.haml
.tabs
    .tabs_item{ class: "#{add_active_class(root_path)}"}
        = link_to '記事一覧', root_path
    .tabs_item{ class: "#{add_active_class(timeline_path)}"}
        = link_to 'タイムライン', timeline_path